name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Fix workspace permissions
        run: sudo chown -R ubuntu:ubuntu "${{ github.workspace }}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and Analysis with SonarQube
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Cleanup SonarQube scanner folder
        run: rm -rf .scannerwork || true

      - name: Trivy FS Scan
        run: trivy fs . > trivyfs.txt

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t sunnytyagi13/swiggy-image:${{ github.sha }} .

      - name: Trivy Image Scan
        run: trivy image sunnytyagi13/swiggy-image:${{ github.sha }} > trivyimage.txt

      - name: Push Docker Image
        run: docker push sunnytyagi13/swiggy-image:${{ github.sha }}

      # -------------------------------------------------------
      # CD STEP: UPDATE ARGOCD GITOPS REPO
      # -------------------------------------------------------
      - name: Checkout ArgoCD Manifests Repo
        uses: actions/checkout@v3
        with:
          repository: sunny008-ux/Deployment-manifest        # <--- CHANGE THIS
          token: ${{ secrets.GITHUB_TOKEN }}               # PAT if private
          path: manifests
          ref: main             # <--- CHANGE THIS TO YOUR REAL DEFAULT BRANCh

      - name: Update Image Tag in K8s Manifests
        run: |
          sed -i "s|image: .*|image: sunnytyagi13/swiggy-image:${{ github.sha }}|g" manifests/deployment.yaml

      - name: Commit & Push Changes
        run: |
          cd manifests
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy new image ${{ github.sha }}"
          git push
